# Generated by Django 6.1.1 on 2026-09-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_refactor_document_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=32)),
                ('extracted_text', models.TextField(blank=True)),
                ('has_text', models.BooleanField(default=False)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('text_sha256', models.CharField(blank=True, max_length=64)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('internal_error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_extraction', to='documents.document')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='text_ext_status_updated_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['processing', 'completed', 'failed'])), name='text_ext_valid_status'), models.CheckConstraint(condition=models.Q(('character_count__gte', 0)), name='text_ext_character_count_nonnegative'), models.CheckConstraint(condition=models.Q(('page_count__gte', 0)), name='text_ext_page_count_nonnegative'), models.CheckConstraint(condition=models.Q(('pages_processed__gte', 0)), name='text_ext_pages_processed_nonnegative')],
            },
        ),
    ]
