"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'documents.apps.DocumentsConfig',
    'extraction.apps.ExtractionConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

_media_root = Path(os.getenv("DJANGO_MEDIA_ROOT", "media"))
MEDIA_ROOT = _media_root if _media_root.is_absolute() else BASE_DIR / _media_root
MEDIA_URL = os.getenv("DJANGO_MEDIA_URL", "/media/")

DOCUMENTS_MAX_UPLOAD_SIZE_BYTES = int(
    os.getenv("DOCUMENTS_MAX_UPLOAD_SIZE_BYTES", str(10 * 1024 * 1024))
)
DOCUMENTS_ALLOWED_UPLOAD_CONTENT_TYPES = [
    content_type.strip().lower()
    for content_type in os.getenv(
        "DOCUMENTS_ALLOWED_UPLOAD_CONTENT_TYPES",
        "application/pdf",
    ).split(",")
    if content_type.strip()
]
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv(
        "DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE",
        str(DOCUMENTS_MAX_UPLOAD_SIZE_BYTES + 1024 * 1024),
    )
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv(
        "DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE",
        str(min(DOCUMENTS_MAX_UPLOAD_SIZE_BYTES, 2 * 1024 * 1024)),
    )
)
EXTRACTION_MAX_PDF_PAGES = int(os.getenv("EXTRACTION_MAX_PDF_PAGES", "100"))
EXTRACTION_MAX_EXTRACTED_TEXT_CHARS = int(
    os.getenv("EXTRACTION_MAX_EXTRACTED_TEXT_CHARS", "1000000")
)
EXTRACTION_MAX_PAGE_CONTENT_BYTES = int(
    os.getenv("EXTRACTION_MAX_PAGE_CONTENT_BYTES", str(5 * 1024 * 1024))
)
# OCR is intentionally bounded. Page usability thresholds accept short native
# text, while classification thresholds require a stronger first-pages signal.
EXTRACTION_NATIVE_SAMPLE_PAGES = int(os.getenv("EXTRACTION_NATIVE_SAMPLE_PAGES", "5"))
EXTRACTION_USABLE_TEXT_MIN_CHARS = int(
    os.getenv("EXTRACTION_USABLE_TEXT_MIN_CHARS", "12")
)
EXTRACTION_USABLE_TEXT_MIN_ALNUM_CHARS = int(
    os.getenv("EXTRACTION_USABLE_TEXT_MIN_ALNUM_CHARS", "8")
)
EXTRACTION_NATIVE_CLASSIFICATION_MIN_TOTAL_CHARS = int(
    os.getenv("EXTRACTION_NATIVE_CLASSIFICATION_MIN_TOTAL_CHARS", "100")
)
EXTRACTION_NATIVE_CLASSIFICATION_MIN_AVERAGE_CHARS = int(
    os.getenv("EXTRACTION_NATIVE_CLASSIFICATION_MIN_AVERAGE_CHARS", "30")
)
EXTRACTION_OCR_MAX_PDF_PAGES = int(
    os.getenv("EXTRACTION_OCR_MAX_PDF_PAGES", str(EXTRACTION_MAX_PDF_PAGES))
)
EXTRACTION_OCR_DPI = int(os.getenv("EXTRACTION_OCR_DPI", "200"))
EXTRACTION_OCR_MAX_IMAGE_PIXELS = int(
    os.getenv("EXTRACTION_OCR_MAX_IMAGE_PIXELS", "20000000")
)
EXTRACTION_OCR_TIMEOUT_SECONDS = int(
    os.getenv("EXTRACTION_OCR_TIMEOUT_SECONDS", "30")
)
EXTRACTION_OCR_MAX_TEXT_CHARS_PER_PAGE = int(
    os.getenv("EXTRACTION_OCR_MAX_TEXT_CHARS_PER_PAGE", "100000")
)
TESSERACT_CMD = os.getenv("TESSERACT_CMD", "")
POPPLER_PATH = os.getenv("POPPLER_PATH", "")

TEXT_CHUNKING_TARGET_CHARS = int(os.getenv("TEXT_CHUNKING_TARGET_CHARS", "1200"))
TEXT_CHUNKING_MAX_CHARS = int(os.getenv("TEXT_CHUNKING_MAX_CHARS", "1600"))
TEXT_CHUNKING_OVERLAP_CHARS = int(os.getenv("TEXT_CHUNKING_OVERLAP_CHARS", "200"))
TEXT_CHUNKING_MIN_CHARS = int(os.getenv("TEXT_CHUNKING_MIN_CHARS", "100"))
TEXT_CHUNKING_MAX_CHUNKS = int(os.getenv("TEXT_CHUNKING_MAX_CHUNKS", "1000"))
TEXT_CHUNKING_MAX_INPUT_CHARS = int(
    os.getenv("TEXT_CHUNKING_MAX_INPUT_CHARS", str(EXTRACTION_MAX_EXTRACTED_TEXT_CHARS))
)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER", "gemini")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "gemini-embedding-2")
EMBEDDING_DIMENSION = int(os.getenv("EMBEDDING_DIMENSION", "768"))
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "16"))
EMBEDDING_MAX_CHUNKS_PER_RUN = int(os.getenv("EMBEDDING_MAX_CHUNKS_PER_RUN", "200"))
EMBEDDING_RETRY_COUNT = int(os.getenv("EMBEDDING_RETRY_COUNT", "2"))
EMBEDDING_RETRY_BACKOFF_SECONDS = float(
    os.getenv("EMBEDDING_RETRY_BACKOFF_SECONDS", "0.25")
)
EMBEDDING_REQUEST_TIMEOUT_SECONDS = int(
    os.getenv("EMBEDDING_REQUEST_TIMEOUT_SECONDS", "30")
)
SEMANTIC_SEARCH_DEFAULT_TOP_K = int(os.getenv("SEMANTIC_SEARCH_DEFAULT_TOP_K", "5"))
SEMANTIC_SEARCH_MAX_TOP_K = int(os.getenv("SEMANTIC_SEARCH_MAX_TOP_K", "20"))
SEMANTIC_SEARCH_MAX_QUERY_CHARS = int(
    os.getenv("SEMANTIC_SEARCH_MAX_QUERY_CHARS", "1000")
)
HYBRID_SEARCH_ENABLED = env_bool("HYBRID_SEARCH_ENABLED", default=True)
HYBRID_VECTOR_CANDIDATES = int(os.getenv("HYBRID_VECTOR_CANDIDATES", "20"))
HYBRID_LEXICAL_CANDIDATES = int(os.getenv("HYBRID_LEXICAL_CANDIDATES", "20"))
HYBRID_RRF_K = int(os.getenv("HYBRID_RRF_K", "60"))
HYBRID_LEXICAL_CONFIG = os.getenv("HYBRID_LEXICAL_CONFIG", "french")
HYBRID_QUERY_EXPANSION_ENABLED = env_bool("HYBRID_QUERY_EXPANSION_ENABLED", default=True)
HYBRID_RERANK_ENABLED = env_bool("HYBRID_RERANK_ENABLED", default=True)
HYBRID_RERANK_EXACT_TERM_WEIGHT = float(
    os.getenv("HYBRID_RERANK_EXACT_TERM_WEIGHT", "0.004")
)
HYBRID_RERANK_VALUE_PATTERN_WEIGHT = float(
    os.getenv("HYBRID_RERANK_VALUE_PATTERN_WEIGHT", "0.018")
)
HYBRID_RERANK_PHRASE_WEIGHT = float(os.getenv("HYBRID_RERANK_PHRASE_WEIGHT", "0.012"))
HYBRID_RERANK_STRUCTURE_WEIGHT = float(
    os.getenv("HYBRID_RERANK_STRUCTURE_WEIGHT", "0.006")
)
HYBRID_RERANK_CONCEPT_MATCH_WEIGHT = float(
    os.getenv("HYBRID_RERANK_CONCEPT_MATCH_WEIGHT", "0.024")
)
HYBRID_RERANK_CONCEPT_MISMATCH_WEIGHT = float(
    os.getenv("HYBRID_RERANK_CONCEPT_MISMATCH_WEIGHT", "0.014")
)
HYBRID_FUZZY_ENABLED = env_bool("HYBRID_FUZZY_ENABLED", default=True)
HYBRID_FUZZY_CANDIDATES = int(os.getenv("HYBRID_FUZZY_CANDIDATES", "8"))
HYBRID_FUZZY_SCAN_LIMIT = int(os.getenv("HYBRID_FUZZY_SCAN_LIMIT", "200"))
HYBRID_FUZZY_MIN_TERM_LENGTH = int(os.getenv("HYBRID_FUZZY_MIN_TERM_LENGTH", "5"))
HYBRID_FUZZY_TERM_LIMIT = int(os.getenv("HYBRID_FUZZY_TERM_LIMIT", "8"))
HYBRID_FUZZY_SCORE_THRESHOLD = float(os.getenv("HYBRID_FUZZY_SCORE_THRESHOLD", "0.86"))
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "gemini")
LLM_MODEL = os.getenv("LLM_MODEL", "models/gemini-3.1-flash-lite")
RAG_TOP_K = int(os.getenv("RAG_TOP_K", "5"))
RAG_MAX_TOP_K = int(os.getenv("RAG_MAX_TOP_K", "20"))
RAG_MAX_QUESTION_CHARS = int(os.getenv("RAG_MAX_QUESTION_CHARS", "1000"))
RAG_MAX_CONTEXT_CHARS = int(os.getenv("RAG_MAX_CONTEXT_CHARS", "6000"))
RAG_QUERY_DECOMPOSITION_ENABLED = env_bool("RAG_QUERY_DECOMPOSITION_ENABLED", default=True)
RAG_MAX_SUBQUERIES = int(os.getenv("RAG_MAX_SUBQUERIES", "4"))
RAG_SUBQUERY_TOP_K = int(os.getenv("RAG_SUBQUERY_TOP_K", "5"))
RAG_LLM_MAX_OUTPUT_TOKENS = int(os.getenv("RAG_LLM_MAX_OUTPUT_TOKENS", "1024"))
RAG_LLM_TEMPERATURE = float(os.getenv("RAG_LLM_TEMPERATURE", "0.2"))
RAG_LLM_RETRY_COUNT = int(os.getenv("RAG_LLM_RETRY_COUNT", "1"))
RAG_LLM_RETRY_BACKOFF_SECONDS = float(
    os.getenv("RAG_LLM_RETRY_BACKOFF_SECONDS", "0.5")
)
RAG_LLM_REQUEST_TIMEOUT_SECONDS = int(
    os.getenv("RAG_LLM_REQUEST_TIMEOUT_SECONDS", "45")
)
PROMPT_ENGINEERING_MAX_QUESTION_CHARS = int(
    os.getenv("PROMPT_ENGINEERING_MAX_QUESTION_CHARS", "1000")
)
PROMPT_ENGINEERING_MAX_CONTEXT_CHARS = int(
    os.getenv("PROMPT_ENGINEERING_MAX_CONTEXT_CHARS", "0")
)
PROMPT_ENGINEERING_MODEL_INPUT_TOKEN_LIMIT = int(
    os.getenv("PROMPT_ENGINEERING_MODEL_INPUT_TOKEN_LIMIT", "1048576")
)
PROMPT_ENGINEERING_MAX_INPUT_TOKENS = int(
    os.getenv("PROMPT_ENGINEERING_MAX_INPUT_TOKENS", "900000")
)
PROMPT_ENGINEERING_TOKEN_SAFETY_MARGIN = int(
    os.getenv("PROMPT_ENGINEERING_TOKEN_SAFETY_MARGIN", "8192")
)
PROMPT_ENGINEERING_ESTIMATED_CHARS_PER_TOKEN = float(
    os.getenv("PROMPT_ENGINEERING_ESTIMATED_CHARS_PER_TOKEN", "3.0")
)
RAPTOR_ENABLED = env_bool("RAPTOR_ENABLED", default=True)
RAPTOR_MAX_LEVELS = int(os.getenv("RAPTOR_MAX_LEVELS", "4"))
RAPTOR_MAX_CLUSTERS = int(os.getenv("RAPTOR_MAX_CLUSTERS", "20"))
RAPTOR_SOFT_CLUSTER_THRESHOLD = float(os.getenv("RAPTOR_SOFT_CLUSTER_THRESHOLD", "0.1"))
RAPTOR_RANDOM_STATE = int(os.getenv("RAPTOR_RANDOM_STATE", "42"))
RAPTOR_MAX_CHUNKS = int(os.getenv("RAPTOR_MAX_CHUNKS", "300"))
RAPTOR_MAX_NODES = int(os.getenv("RAPTOR_MAX_NODES", "1000"))
RAPTOR_MAX_SUMMARY_CONTEXT_CHARS = int(
    os.getenv("RAPTOR_MAX_SUMMARY_CONTEXT_CHARS", "12000")
)
RAPTOR_MAX_SUMMARY_CHARS = int(os.getenv("RAPTOR_MAX_SUMMARY_CHARS", "2000"))
RAPTOR_RETRIEVAL_TOP_K = int(os.getenv("RAPTOR_RETRIEVAL_TOP_K", "6"))
RAPTOR_MAX_TOP_K = int(os.getenv("RAPTOR_MAX_TOP_K", "20"))
RAPTOR_MAX_QUESTION_CHARS = int(os.getenv("RAPTOR_MAX_QUESTION_CHARS", "1000"))
RAPTOR_MAX_CONTEXT_CHARS = int(os.getenv("RAPTOR_MAX_CONTEXT_CHARS", "6000"))
RAPTOR_CHILD_EXPANSION_LIMIT = int(os.getenv("RAPTOR_CHILD_EXPANSION_LIMIT", "2"))
RAPTOR_FACTUAL_LEAF_CANDIDATES = int(os.getenv("RAPTOR_FACTUAL_LEAF_CANDIDATES", "8"))
RAPTOR_MULTI_INTENT_ENABLED = env_bool("RAPTOR_MULTI_INTENT_ENABLED", default=True)
RAPTOR_MAX_SUBINTENTS = int(os.getenv("RAPTOR_MAX_SUBINTENTS", "4"))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
